### ISSUE TITLE
the git-author formula is out of date

### ISSUE THREAD

**Issue by cwlbraa** [pivotal-legacy/homebrew-tap#129]
The version in the tap doesn't work with the addition of git-together's `--global` flag. 

Installing via the repo's setup script is troublesome due to permissions issues.

Please update it. Thanks!

**Comment by professor** [comment]
Ok, we just updated git-author to 1.0.3 which supports --global flag. Let us know if this solves the problem: https://github.com/pivotal-legacy/homebrew-tap/commit/645ce0208fb8c4a357d7b8c51c3008261bb8938b

**Comment by cwlbraa** [comment]
you're a hero! this looks like it should solve the last couple issues we have.
